### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by gr8nishan** [pawangeek/Competitions-ML#2]
Hi Pawan,

I had a query regarding the pre-processing steps. Are these steps based on your findings of the dataset or they are generalized. Can be use in most of the scenarios.

If it is based on the scenario how did you go about detecting them.

**Comment by pawangeek** [comment]
Hello @gr8nishan,

Some of the preprocessing steps are generalized like contraction mapping, punctuation spacing, cleaning punctuation for text data

And some of them are based on dataset like bad words removal by checking oov score on glove/fasttext, removing some lines which are common and not contain any related information like lines have substrings like 'help center', 'information brochure' etc this can be decided easily by networkx ( have lowest score). Remove sentences before sentence containing the corresponding drug which helps me to reduce data of single column
